trigger:
  branches:
    include:
      - main
pool:
  vmImage: 'ubuntu-latest'
steps:
  - script: echo 'Starting Docker Build and Compose'
    displayName: 'Starting Docker Build and Compose'
  - task: Docker@2
    displayName: 'Build Docker Image'
    inputs:
      command: 'build'
      Dockerfile: '**/Dockerfile'
      tags: 'latest'
  - task: Docker@2
    displayName: 'Push Docker Image to Registry'
    inputs:
      command: 'push'
      tags: 'latest'
      containerRegistry: '86d80b68-84e6-4132-8050-f732fee02a6c'
  - task: Docker@2
    displayName: 'Docker Compose Up'
    inputs:
      command: 'composeUp'
      dockerComposeFile: '**/docker-compose.yml'
      removeContainersOnPull: true
      detachedService: true
